export type Portfolio = {
  initial_balance: number;
  cash_balance: number;
  invested_value: number;
  portfolio_value: number;
  realized_pnl: number;
  unrealized_pnl: number;
  total_pnl: number;
  total_return_pct: number;
  open_positions: number;
};
export type Analysis = {
  id: number;
  symbol: string;
  price: number;
  score: number;
  trend: string;
  market_structure: string;
  setup: string;
  decision: string;
  reason: string;
  data_source: string;
  analyzed_at: string;
  signal_candle_time?: string;
  data_valid?: boolean;
  ai_status?: string;
  ai_provider?: string;
  ai_model?: string;
  ai_result?: AISecondOpinion;
  details: {
    ai?: AISecondOpinion;
    analysis_context?: {
      daily_candle_time: string;
      hourly_candle_time: string;
      entry_candle_time: string;
      analysis_at: string;
      freshness: Record<string, string>;
    };
    timeframes?: Record<string, { label: string }>;
    structure?: {
      label: string;
      swings: Array<{
        timestamp: string;
        price: number;
        type: string;
        strength: number;
      }>;
    };
    momentum?: { label: string; rsi: number };
    volume?: { rvol: number; confirmed: boolean; quality?: string };
    volatility?: { atr: number; atr_pct: number };
    levels?: {
      support: number;
      resistance: number;
      support_zone?: PriceZone;
    resistance_zone?: PriceZone;
      zones?: PriceZone[];
    };
    candle_quality?: Record<string, number | boolean>;
    risk_reward?: number;
    score_breakdown?: Record<string, number>;
    setup?: { entry_area: number; invalidation_level: number; target: number };
    setup_quality?: number;
    setup_reason?: string;
    setup_rejections?: string[];
    universe?: { status: string; reason: string; affordable: boolean };
    technical_score?: number;
    indicators?: IndicatorSnapshot;
    relative_strength?: RelativeStrength;
    news?: { status: string; news_score?: number; items: NewsItem[] };
  };
};
export type AISecondOpinion = {
  status: string;
  reason: string;
  provider: string;
  model: string;
  execution_authority: false;
  verdict?: "CONFIRM" | "WATCH" | "AVOID";
  confidence?: number;
  summary?: string;
  strengths?: string[];
  risks?: string[];
  invalidation_note?: string;
  combined_ai?: CombinedAI;
};
export type CombinedAI={technical_verdict:string;news_sentiment:string;combined_view:string;confidence:number;summary:string;main_risks:string[];execution_authority:false};
export type IndicatorSnapshot={ema20?:number;ema50?:number;ema200?:number;rsi?:number;macd?:{macd:number;signal:number;histogram:number};bollinger?:{upper:number;middle:number;lower:number};atr?:number;atr_pct?:number;vwap?:number;rvol?:number;relative_volume?:number;volume_sma20?:number;volatility_20d?:number;trend_strength?:number;price_distance_ema20_pct?:number;price_distance_ema50_pct?:number;price_distance_ema200_pct?:number};
export type RelativeStrength={label:string;stock_return_1d?:number;xu100_return_1d?:number;relative_strength_1d?:number;stock_return_5d?:number;xu100_return_5d?:number;relative_strength_5d?:number;stock_return_20d?:number;xu100_return_20d?:number;relative_strength_20d?:number};
export type NewsReaction={id:number;news_id:number;symbol:string;price_before?:number;previous_close?:number;next_open?:number;next_close?:number;gap_pct?:number;return_15m?:number;return_1h?:number;return_1d?:number;return_5d?:number;xu100_return_1d?:number;abnormal_return_1d?:number;volume_change?:number;rvol_after?:number;evaluated_at?:string;last_evaluation_at?:string;status:string};
export type NewsItem={id?:number;symbol?:string;company_name?:string;source:string;source_id?:string;title:string;content?:string;url:string;category:string;status?:string;published_at:string;first_seen_at?:string;fetched_at?:string;updated_at?:string;telegram_sent?:boolean;telegram_sent_at?:string;overnight_news?:boolean;ai_status?:string;ai_sentiment?:"POSITIVE"|"NEUTRAL"|"NEGATIVE";ai_importance?:number;ai_summary?:string;ai_horizon?:string;ai_risks?:string[];ai_tags?:string[];ai_model?:string;reaction?:NewsReaction};
export type NewsHealth={enabled:boolean;configured:boolean;status:string;sources:Record<string,{status:string;last_fetch?:string;new_items:number;parse_errors:number;error?:string}>;groq_processed:number;pending_ai:number;last_24h:number;important_24h:number;overnight_24h:number;kap_24h:number;errors:number};
export type MarketSnapshot={id?:number;symbol:string;timeframe?:string;timestamp:string;status:string;price?:number;ema20?:number;ema50?:number;ema200?:number;rsi?:number;macd?:number;macd_signal?:number;macd_histogram?:number;bb_upper?:number;bb_middle?:number;bb_lower?:number;atr?:number;atr_pct?:number;vwap?:number;rvol?:number;volume_sma20?:number;trend?:string;market_structure?:string;swing_high?:number;swing_low?:number;support?:number;resistance?:number;bos?:string;choch?:string;setup?:string;setup_quality?:number;technical_score?:number;risk_reward?:number;relative_strength_1d?:number;relative_strength_5d?:number;relative_strength_20d?:number;xu100_price?:number;data_source?:string;data_quality?:string;reason?:string};
export type MarketMemoryHealth={status:string;snapshot_count:number;reaction_count:number;news_count:number;candle_count:number;symbols:number;recorded_count:number;reconstructed_count:number;error_count:number;timeframes:Record<string,number>;last_snapshot?:string;last_snapshot_at?:string;last_news?:string};
export type BackfillState={task:string;status:string;cursor:number;processed_items:number;last_run_at?:string;error?:string;details?:Record<string,unknown>};
export type BackfillStatus={status:string;cursor:number;universe_total:number;completed_symbols:number;remaining_symbols:number;progress_pct:number;candle_count:number;last_symbol?:string;last_timeframe?:string;last_run_at?:string;last_error?:string;timeframes:Record<string,number>;tasks:BackfillState[]};
export type NewsMetrics={total_news:number;news_last_24h:number;news_last_7d:number;news_last_30d:number;symbol_linked:number;unmatched:number;ai_processed:number;ai_pending:number;overnight_count:number;reactions_pending:number;reactions_partial:number;reactions_complete:number};
export type NewsSourceHealth={source:string;name:string;type:string;status:string;enabled:boolean;last_success_at?:string;last_item_at?:string;items_fetched:number;items_inserted:number;duplicates:number;consecutive_failures:number;last_error?:string;supports_backfill:boolean};
export type ReactionQueueStatus={pending:number;waiting_market_open:number;waiting_15m:number;waiting_1h:number;waiting_1d:number;waiting_5d:number;complete:number;error:number;total:number;progress_pct:number};
export type CollectionActivity={id:number;created_at:string;module:string;subject?:string;action:string;status:string;detail?:string};
export type EventStudy={category:string;news_count:number;positive_ai_count:number;negative_ai_count:number;avg_return_1d?:number;median_return_1d?:number;avg_return_5d?:number;positive_rate?:number;avg_abnormal_return?:number;avg_volume_change?:number};
export type PriceZone = {
  low: number;
  high: number;
  center: number;
  touch_count: number;
  strength: number;
  side: string;
};
export type WatchItem = {
  symbol: string;
  score: number;
  setup: string;
  status: string;
  reason: string;
  last_analyzed_at: string;
  price?: number;
  setup_quality?: number;
  trend?: string;
  structure?: string;
  support?: number;
  resistance?: number;
  rr?: number;
};
export type Position = {
  id: number;
  symbol: string;
  quantity: number;
  entry_price: number;
  current_price: number;
  stop_price: number;
  target_price: number;
  entry_fees: number;
  setup_type: string;
  signal_score: number;
  entry_reason: string;
  opened_at: string;
  run_id?: string;
};
export type Trade = {
  id: number;
  symbol: string;
  quantity: number;
  entry_price: number;
  exit_price: number;
  fees: number;
  slippage_cost: number;
  realized_pnl: number;
  return_pct: number;
  setup_type: string;
  signal_score: number;
  entry_reason: string;
  exit_reason: string;
  entry_time: string;
  exit_time: string;
  run_id?: string;
};
export type Decision = {
  id: number;
  symbol?: string;
  category: string;
  decision: string;
  reason: string;
  score?: number;
  created_at: string;
};
export type Candle = {
  timestamp: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  indicators?: IndicatorSnapshot;
};
export type Snapshot = { timestamp: string; portfolio_value: number };
export type DataHealth = {
  provider: string;
  mode: string;
  status: string;
  last_successful_fetch?: string;
  scanner_last_run?: string;
  scanner_duration_ms?: number;
  valid_symbols: number;
  failed_symbols: number;
  stale_symbols: number;
  errors: Array<{ symbol: string; error: string }>;
  funnel?: Record<string, number>;
};
export type ScannerStatus = {
  status: "NO_SCAN" | "RUNNING" | "COMPLETE" | "COMPLETE_WITH_ERRORS";
  market_status: "MARKET OPEN" | "MARKET CLOSED";
  provider: string;
  auto_worker: boolean;
  scanner_symbol_limit: number;
  manual_scan_symbol_limit: number;
  watchlist_score: number;
  entry_score: number;
  next_automatic_scan?: string | null;
  watchlist_count: number;
  latest_analysis_symbols: number;
  analysis_rows: number;
  last_scan?: {
    started_at: string;
    completed_at?: string;
    duration_ms?: number;
    total_symbols: number;
    valid_symbols: number;
    failed_symbols: number;
    stale_symbols: number;
    watchlist_count: number;
    signals: number;
    entries: number;
    errors: Array<{symbol:string;error:string}>;
    funnel: Record<string,number>;
  } | null;
  recent_scans: Array<{
    id:number;
    started_at:string;
    completed_at?:string;
    total_symbols:number;
    valid_symbols:number;
    failed_symbols:number;
    watchlist_count:number;
    signals:number;
    entries:number;
  }>;
};

export type ScannerRunResponse = {
  status: "completed" | "market_closed" | "already_running" | "wrong_mode";
  analyzed: number;
  duration_ms?: number;
  errors: Array<{ symbol: string; error: string }>;
  funnel?: Record<string, number>;
  results: Array<{
    symbol: string;
    score: number;
    decision: string;
    source: string;
    universe_status: string;
  }>;
};

export type StrategyHealth = {
  status: string;
  dataset?: {
    source: string;
    start: string;
    end: string;
    trading_days: number;
    symbols: string[];
  };
  score_before?: ScoreSummary;
  score_after?: ScoreSummary;
  setup_counts?: Record<string, number>;
  signal_funnel?: Record<string, number>;
  top_rejections?: Array<[string, number]>;
  last_replay?: {
    starting_equity: number;
    ending_equity: number;
    net_pnl: number;
    return_pct: number;
    trades: number;
    wins: number;
    losses: number;
    max_drawdown_pct: number;
    benchmark_return_pct?: number;
  };
  v4?: {
    status: string;
    strategy_config_hash?: string;
    research_period?: { start?: string; end?: string };
    oos_period?: { start?: string; end?: string };
    warmup_rows: number;
    evaluation_rows: number;
    oos_trade_count: number;
    sample_confidence?: string;
    exit_diagnostics_scope?: string;
    exit_diagnostics?: {
      median_holding_hours: number;
      average_mfe: number;
      average_mae: number;
      stops: number;
      stopped_then_recovered_pct: Record<string, number>;
    };
  };
};
export type ScoreSummary = {
  min: number;
  max: number;
  mean: number;
  median: number;
  distribution: Record<string, number>;
};
export type ForwardStatus = {
  status: "RUNNING" | "PAUSED";
  run_id: string;
  forward_test_started_at: string;
  running_days: number;
  strategy_version: string;
  strategy_config_hash: string;
  provider: string;
  operation_mode: string;
  market_status: "MARKET OPEN" | "MARKET CLOSED";
  completed_scans: number;
  signals: number;
  trades: number;
  trades_today: number;
  watchlist_count: number;
  daily_pnl: number;
  portfolio: Portfolio;
  scanner: {
    last_scan?: string;
    last_processed_candle?: string;
    next_expected_candle?: string;
    symbols_scanned: number;
    valid: number;
    failed: number;
    watchlist: number;
    signals: number;
    orders: number;
  };
  worker: {
    embedded: boolean;
    always_on: boolean;
    current_cadence_minutes: number;
    position_check_minutes: number;
    strategy_candle_minutes: number;
  };
  performance: {
    trades: number;
    wins: number;
    losses: number;
    win_rate: number;
    profit_factor?: number;
    average_win: number;
    average_loss: number;
    max_drawdown_pct: number;
    fees: number;
    slippage: number;
    average_holding_hours: number;
    average_exposure_pct: number;
    sample_warning?: string;
  };
  benchmark: {
    symbol: string;
    start_price?: number;
    latest_price?: number;
    return_pct?: number;
    updated_at?: string;
  };
};
